/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.umsu.pembahasan;

import javax.swing.JOptionPane;

/**
 *
 * @author amrullahaam
 */
public class OPobject extends javax.swing.JFrame {

    /**
     * Creates new form OPobject
     */
    public OPobject() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnpesan = new javax.swing.JButton();
        btninput = new javax.swing.JButton();
        btnkonfirmasi = new javax.swing.JButton();
        btnpilihan = new javax.swing.JButton();
        btnkeluar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setBackground(new java.awt.Color(204, 255, 204));
        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel1.setText("Belajar OP- Object");

        btnpesan.setText("Pesan Teks");
        btnpesan.setName("btnpesan"); // NOI18N
        btnpesan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpesanActionPerformed(evt);
            }
        });

        btninput.setText("Input Teks");
        btninput.setName("btninput"); // NOI18N
        btninput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btninputActionPerformed(evt);
            }
        });

        btnkonfirmasi.setText("Teks Konfirmasi");
        btnkonfirmasi.setName("btnkonfirmasi"); // NOI18N
        btnkonfirmasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkonfirmasiActionPerformed(evt);
            }
        });

        btnpilihan.setText("Teks Pilihan");
        btnpilihan.setName("btnpilihan"); // NOI18N
        btnpilihan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpilihanActionPerformed(evt);
            }
        });

        btnkeluar.setText("Keluar");
        btnkeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkeluarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnpesan)
                    .addComponent(btnkonfirmasi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btninput)
                    .addComponent(btnpilihan))
                .addGap(65, 65, 65))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnkeluar)
                .addGap(132, 132, 132))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnpesan)
                    .addComponent(btninput))
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnkonfirmasi)
                    .addComponent(btnpilihan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(btnkeluar)
                .addGap(38, 38, 38))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnpesanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpesanActionPerformed
//        JOptionPane.showMessageDialog(this,"Ini Pesan Teks");
        JOptionPane.showMessageDialog(this, "Hallo guys...");
    }//GEN-LAST:event_btnpesanActionPerformed

    private void btninputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btninputActionPerformed
        String InputTeks = JOptionPane.showInputDialog("Masukkan Pesan Anda :");
        JOptionPane.showMessageDialog(this,"Kamu Menulis "+ InputTeks);
    }//GEN-LAST:event_btninputActionPerformed

    private void btnkonfirmasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkonfirmasiActionPerformed
        int Pilihan = JOptionPane.showConfirmDialog(this, "Silahkan Pilih");
        switch (Pilihan) {
            case JOptionPane.YES_OPTION:
                JOptionPane.showMessageDialog(this,"Kamu Menjawab Ya");
                break;
            case JOptionPane.NO_OPTION:
                JOptionPane.showMessageDialog(this,"Kamu Menjawab Tidak");
                break;
            case JOptionPane.CANCEL_OPTION:
                JOptionPane.showMessageDialog(this,"Kamu Menjawab Batal");
                
        }
    }//GEN-LAST:event_btnkonfirmasiActionPerformed

    private void btnpilihanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpilihanActionPerformed
       int Pilihan = JOptionPane.showOptionDialog(this, "Ingin Keluar?",
               "Keluar", JOptionPane.YES_NO_OPTION,
               JOptionPane.QUESTION_MESSAGE, null, null, null);
       
        if (Pilihan == JOptionPane.YES_OPTION) {
            JOptionPane.showMessageDialog(this,"Keluar Aplikasi");
            System.exit(0);
        }
    }//GEN-LAST:event_btnpilihanActionPerformed

    private void btnkeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkeluarActionPerformed
        JOptionPane.showMessageDialog(this,"gimana sudah paham?");
    }//GEN-LAST:event_btnkeluarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OPobject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OPobject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OPobject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OPobject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OPobject().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btninput;
    private javax.swing.JButton btnkeluar;
    private javax.swing.JButton btnkonfirmasi;
    private javax.swing.JButton btnpesan;
    private javax.swing.JButton btnpilihan;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
